### ISSUE TITLE
1.2.0: Can't connect to 35.186.190.72:9190

### ISSUE THREAD

**Issue by joesixpack** [OpenFuturePlatform/open-chain#3]
![image](https://user-images.githubusercontent.com/23145642/47349042-9aaffb00-d667-11e8-99c5-731b41ba626d.png)

**Comment by annashunkoby** [comment]
`35.186.190.72` is the address of one of the 21 boot nodes we have.

_Can not connect_ warning can appear when an application on a remote node is not responding or crashed or someone uses that node for testing.

However, if you can't connect to one root node you still have 20 other. This warning won't affect the application.

This version is a testnet. There might be some connection warnings to the root nodes.
