### ISSUE TITLE
Browser Issues with Creating/Restoring Wallets

### ISSUE THREAD

**Issue by joesixpack** [OpenFuturePlatform/open-chain#6]
Some interesting behavior with Chromium (61.0.3163.79) and Internet Explorer (11.0.9600.19266).

In IE, you can CONFIRM the seed phrase without first exporting, but not in Chrome.

In Chrome, the DONE button after creating a password works, but not in IE.

**Comment by ruslanys** [comment]
Hello @joesixpack. First of all, thank you very much for your feedback and help in finding bugs.

We have tested the application in the Chromium(71.0.3578.98), Chrome(72.0.3626.119) and Firefox(65.0.1), and it works correctly.

Unfortunately, web browsers, like IE and Microsoft Edge doesn't work correctly with a crypto object in our case. We tried to found different ways, used polyfills, but none of the methods led to a working result.
We will keep in mind problems in IE/Edge and fix them if it is possible someday.

Please note, that we do not support IE/Edge officially.

Thank you again for your feedback, appreciate it. 🙏
